language: java
sudo: false # faster builds

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.0/codacy-coverage-reporter-4.0.0-assembly.jar


install:
- ./mvnw install -Dmaven.javadoc.skip=true -B -V -P dev

script: "./mvnw verify -P all-tests"

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco-ut/jacoco.xml  --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco-it/jacoco.xml  --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
  - ./mvnw  sonar:sonar -Dsonar.host.url=http://jenkins.slave-01.cod3byte.com
  
