language: java
sudo: false # faster builds

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)


install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: "mvn clean verify -P all-tests"

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco-ut/jacoco.xml  --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco-it/jacoco.xml  --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
  
